# Generated by Django 6.0.5 on 2026-05-20 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_cell_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('K', models.IntegerField(help_text='Number of unique neighbors = len(neighbor_order)')),
                ('mean_codisp', models.FloatField(help_text='Baseline mean CoDisp score from training')),
                ('std_codisp', models.FloatField(help_text='Baseline std CoDisp score from training')),
                ('training_rows', models.IntegerField(default=0, help_text='Number of MR rows used for training')),
                ('neighbor_order', models.JSONField(default=list, help_text='Ordered list of ALL unique neighbor cell IDs (defines feature columns)')),
                ('neighbor_stats', models.JSONField(default=dict, help_text='Per-neighbor RSRP/RSRQ mean/std statistics for Z-score computation')),
                ('num_trees', models.IntegerField(default=150, help_text='Number of RRCF trees')),
                ('tree_size', models.IntegerField(default=1024, help_text='Max data points per tree')),
                ('last_trained', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serving_cell_id'],
            },
        ),
        migrations.CreateModel(
            name='DetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_file', models.CharField(max_length=500)),
                ('total_rows_scanned', models.IntegerField(default=0)),
                ('total_anomalies', models.IntegerField(default=0)),
                ('total_cells_scanned', models.IntegerField(default=0)),
                ('threshold_mult', models.FloatField(default=1.0)),
                ('z_threshold', models.FloatField(default=2.0)),
                ('min_anomaly_score', models.FloatField(default=4.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_dir', models.CharField(blank=True, default='', max_length=500)),
                ('error_log', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('train_file', models.CharField(max_length=500)),
                ('model_dir', models.CharField(blank=True, default='', max_length=500)),
                ('num_trees', models.IntegerField(default=150)),
                ('tree_size', models.IntegerField(default=1024)),
                ('min_samples', models.IntegerField(default=50)),
                ('total_cells_trained', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_cell_id', models.CharField(max_length=50)),
                ('neighbor_id', models.CharField(max_length=50)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('event_count', models.IntegerField(default=0, help_text='Anomaly events in this window')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_windows', to='detection.detectionrun')),
            ],
            options={
                'ordering': ['-event_count'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_cell_id', models.CharField(db_index=True, max_length=50)),
                ('row_index', models.IntegerField()),
                ('datetime_raw', models.DateTimeField(blank=True, null=True)),
                ('avg_codisp', models.FloatField(help_text='Average CoDisp score across 150 RRCF trees')),
                ('threshold', models.FloatField(help_text='mean_codisp + threshold_mult * std_codisp')),
                ('rrcf_flagged', models.BooleanField(default=False, help_text='Layer 1: avg_codisp > threshold')),
                ('zscore_flagged', models.BooleanField(default=False, help_text='Layer 2: any neighbor combined Z-score > min_anomaly_score')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='detection.detectionrun')),
            ],
            options={
                'ordering': ['-avg_codisp'],
            },
        ),
        migrations.CreateModel(
            name='AbnormalNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_cell_id', models.CharField(max_length=50)),
                ('neighbor_id', models.CharField(db_index=True, max_length=50)),
                ('event_count', models.IntegerField(default=0, help_text='Total anomaly events for this neighbor')),
                ('window_count', models.IntegerField(default=0, help_text='Number of 30-min windows where this neighbor triggered')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_neighbors', to='detection.detectionrun')),
            ],
            options={
                'ordering': ['-event_count'],
            },
        ),
        migrations.CreateModel(
            name='NeighborAnomalyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_cell_id', models.CharField(max_length=50)),
                ('neighbor_id', models.CharField(db_index=True, max_length=50)),
                ('anomaly_score', models.FloatField(help_text='Combined Z-score: sqrt(rsrp_z^2 + rsrq_z^2)')),
                ('rsrp', models.FloatField(blank=True, help_text='Observed RSRP in dBm (-140 to -44)', null=True)),
                ('rsrq', models.FloatField(blank=True, help_text='Observed RSRQ in dB (-20 to -3)', null=True)),
                ('rsrp_z', models.FloatField(blank=True, help_text='RSRP Z-score vs training mean', null=True)),
                ('rsrq_z', models.FloatField(blank=True, help_text='RSRQ Z-score vs training mean', null=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_details', to='detection.anomaly')),
            ],
            options={
                'ordering': ['-anomaly_score'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbor_id', models.CharField(db_index=True, max_length=50)),
                ('sum_score', models.FloatField(help_text='Total cumulative anomaly score')),
                ('occurrence_count', models.IntegerField(default=0, help_text='Number of times this neighbor was flagged')),
                ('affected_serving_cells', models.JSONField(default=list, help_text='List of serving cells where this neighbor appeared')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_neighbors', to='detection.detectionrun')),
            ],
            options={
                'ordering': ['-sum_score'],
            },
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['run', 'serving_cell_id'], name='detection_a_run_id_ad6138_idx'),
        ),
    ]
