# Generated by Django 6.0.5 on 2026-05-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_cell_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('cell_name', models.CharField(blank=True, default='', max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('technology', models.CharField(choices=[('LTE', 'LTE'), ('5G-NR', '5G NR'), ('3G', '3G')], default='LTE', max_length=10)),
                ('band', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['global_cell_id'],
            },
        ),
    ]
