# Generated by Django 5.1.2 on 2026-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_filename', models.CharField(max_length=255)),
                ('output_dir', models.TextField()),
                ('total_rows', models.IntegerField(default=0)),
                ('total_anomalies', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=32)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
